apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sudoker-fe
  name: sudoker-fe-deployment
  namespace: cd-coding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sudoker-fe
  template:
    metadata:
      labels:
        app: sudoker-fe
    spec:
      imagePullSecrets:
        - name: coding-registry-cred-8438001
      containers:
        - image: 'i-soft-docker.pkg.coding.net/sudoker/sudoker-fe/sudoker-fe'
          name: sudoker-fe
          ports:
            - containerPort: 80